"""
Report generation for CCDC hardening framework
Generates detailed markdown reports for blue team onboarding
"""

import logging
import os
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates comprehensive hardening reports with blue team quick reference"""

    def __init__(self, server_info, os_family, modules_map):
        self.server_info = server_info
        self.os_family = os_family
        self.modules_map = modules_map

    def generate_report(self, host_label: str, results: dict, summary: str) -> str:
        """Generate markdown report for the host"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_dir = Path("logs/reports")
        report_dir.mkdir(parents=True, exist_ok=True)
        report_path = report_dir / f"REPORT_{host_label}_{timestamp}.md"

        try:
            with open(report_path, "w") as f:
                self._write_header(f, host_label)
                self._write_system_info(f)
                self._write_failures_summary(f, results)
                self._write_user_management_changes(f, results)
                self._write_sudoers_config(f)
                self._write_network_info(f)
                self._write_running_services(f)
                self._write_blue_team_reference(f, results)
                f.write("---\nGenerated by CCDC Fabric Deploy\n")

            logger.info(f"Report generated: {report_path}")
            return str(report_path)

        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
            return ""

    def _write_header(self, f, host_label: str):
        """Write report header"""
        f.write(f"# Hardening Report: {host_label}\n")
        f.write(f"**Date**: {datetime.now().isoformat()}\n")
        f.write(f"**Host**: {self.server_info.hostname} ({self.os_family})\n\n")

    def _write_system_info(self, f):
        """Write system information section"""
        f.write("## System Information\n")
        os_info = self.server_info.os
        f.write("| Property | Value |\n")
        f.write("|----------|-------|\n")
        f.write(f"| **OS** | {os_info.distro} {os_info.version} |\n")
        f.write(f"| **Kernel** | {os_info.kernel} |\n")
        f.write(f"| **Architecture** | {os_info.architecture} |\n")
        f.write(f"| **Init System** | {self.server_info.init_system} |\n")
        pkg_mgrs = (
            ", ".join(self.server_info.package_managers)
            if self.server_info.package_managers
            else "None detected"
        )
        f.write(f"| **Package Managers** | {pkg_mgrs} |\n")
        f.write(f"| **Default Shell** | {self.server_info.default_shell} |\n")
        f.write(f"| **Sudo Group** | {self.server_info.sudo_group} |\n")
        f.write("\n")

    def _write_failures_summary(self, f, results: dict):
        """Write failures summary section"""
        all_failures = []
        for module_name, module_results in results.items():
            for r in module_results:
                if not r.success:
                    all_failures.append(
                        (module_name, r.description, r.error or "Unknown error")
                    )

        if all_failures:
            f.write("## ⚠️ Failures Summary\n")
            f.write(f"**Total Failures**: {len(all_failures)}\n\n")
            f.write(
                "The following items failed and may need **manual intervention**:\n\n"
            )
            for module_name, desc, error in all_failures:
                # Truncate long errors for readability
                error_short = error[:200] + "..." if len(error) > 200 else error
                f.write(f"- [ ] **{module_name}**: {desc}\n")
                f.write(f"  - Error: `{error_short}`\n")
            f.write("\n")
        else:
            f.write("## ✅ No Failures\n")
            f.write("All hardening steps completed successfully.\n\n")



    def _write_user_management_changes(self, f, results: dict):
        """Write user management changes section"""
        f.write("## User Management Changes\n")
        user_res = results.get("user_hardening", [])
        pwd_log = next(
            (r.output for r in user_res if r.command.startswith("write_password_log")),
            None,
        )
        if pwd_log and os.path.exists(pwd_log):
            f.write(f"**Password Log**: `{pwd_log}`\n\n")
            try:
                f.write("### Password Log Content\n")
                f.write("```\n")
                f.write(Path(pwd_log).read_text())
                f.write("\n```\n")
            except Exception:
                f.write("*(Could not read password log)*\n")
        else:
            f.write("*No password changes recorded or log not found.*\n")

        # Report locked users
        locked_users = []
        for r in user_res:
             if r.success and "Lock unauthorized user:" in r.description:
                 # Description format: "Lock unauthorized user: <username>"
                 user = r.description.split(":", 1)[1].strip()
                 locked_users.append(user)
        
        if locked_users:
            f.write("\n### Locked Users\n")
            f.write(f"*{len(locked_users)} unauthorized users were locked:*\n\n")
            for user in sorted(locked_users):
                f.write(f"- {user}\n")
        f.write("\n")

    def _write_sudoers_config(self, f):
        """Write sudoers configuration section"""
        f.write("## Sudoers Configuration\n")
        sudoers_dump = getattr(self.server_info, "sudoers_dump", None)
        if sudoers_dump:
            f.write("### /etc/sudoers Dump\n")
            f.write("```\n")
            f.write(sudoers_dump)
            f.write("\n```\n")
        else:
            f.write("*Sudoers dump not available.*\n")
        f.write("\n")

    def _write_network_info(self, f):
        """Write network information section"""
        f.write("## Network Information\n")
        open_ports = self.server_info.network.open_ports
        ports_str = ", ".join(open_ports) if open_ports else "None detected"
        f.write(f"- **Open Ports**: {ports_str}\n")
        route = (
            self.server_info.network.default_route.strip()
            if self.server_info.network.default_route
            else "Not available"
        )
        f.write(f"- **Default Route**: {route}\n")
        f.write("\n")



    def _write_running_services(self, f):
        """Write running services section"""
        f.write("## Running Services\n")
        services = self.server_info.services
        if services:
            f.write(f"*{len(services)} services detected*\n\n")
            # Show as compact list
            for svc in sorted(services)[:30]:
                f.write(f"- {svc}\n")
            if len(services) > 30:
                f.write(f"- *...and {len(services) - 30} more*\n")
        else:
            f.write("*No services detected*\n")
        f.write("\n")

    def _write_blue_team_reference(self, f, results: dict):
        """Write practical blue team onboarding guide to report"""
        f.write("## Blue Team Quick Reference\n\n")
        f.write(
            "This section provides practical commands for managing this system during the competition.\n\n"
        )

        # Get the UserHardeningModule to determine which commands are available
        user_module = self.modules_map.get("user_hardening")
        if user_module:
            user_manager = user_module.user_manager
            sudo_group = self.server_info.sudo_group

            f.write("### User Management\n\n")
            f.write(f"**Note**: This system uses `{sudo_group}` for sudo access.\n\n")

            # Add a new user
            f.write("#### Add a New User\n")
            if user_manager._has("useradd"):
                f.write("```bash\n")
                f.write("# Create user with home directory\n")
                f.write("sudo useradd -m -s /bin/bash username\n\n")
                f.write("# Set password\n")
                f.write("sudo passwd username\n")
                f.write("```\n\n")
            elif user_manager._has("adduser"):
                f.write("```bash\n")
                f.write("# Create user (interactive or non-interactive)\n")
                f.write("sudo adduser username\n")
                f.write("# OR for non-interactive:\n")
                f.write("sudo adduser --disabled-password --gecos '' username\n")
                f.write("sudo passwd username\n")
                f.write("```\n\n")
            elif user_manager._has("pw"):
                f.write("```bash\n")
                f.write("# BSD: Create user with home directory\n")
                f.write("sudo pw useradd -n username -m -s /bin/sh\n\n")
                f.write("# Set password\n")
                f.write("sudo pw usermod -n username -h 0  # then enter password\n")
                f.write("```\n\n")
            elif user_manager._has("dscl"):
                f.write("```bash\n")
                f.write("# macOS: Create user (requires manual UID selection)\n")
                f.write("# See system administrator for detailed steps\n")
                f.write("```\n\n")

            # Change password
            f.write("#### Change User Password\n")
            if user_manager._has("passwd"):
                f.write("```bash\n")
                f.write("# Change password for any user\n")
                f.write("sudo passwd username\n\n")
                f.write("# Change your own password\n")
                f.write("passwd\n")
                f.write("```\n\n")
            elif user_manager._has("chpasswd"):
                f.write("```bash\n")
                f.write("# Change password non-interactively\n")
                f.write("echo 'username:newpassword' | sudo chpasswd\n")
                f.write("```\n\n")
            elif user_manager._has("pw"):
                f.write("```bash\n")
                f.write("# BSD: Change password\n")
                f.write("sudo pw usermod -n username -h 0  # then enter password\n")
                f.write("```\n\n")

            # Add to sudoers
            f.write("#### Grant Sudo Access\n")
            if user_manager._has("usermod"):
                f.write("```bash\n")
                f.write(f"# Add user to {sudo_group} group\n")
                f.write(f"sudo usermod -aG {sudo_group} username\n\n")
                f.write("# Verify membership\n")
                f.write("groups username\n")
                f.write("```\n\n")
            elif user_manager._has("gpasswd"):
                f.write("```bash\n")
                f.write(f"# Add user to {sudo_group} group\n")
                f.write(f"sudo gpasswd -a username {sudo_group}\n\n")
                f.write("# Verify membership\n")
                f.write("groups username\n")
                f.write("```\n\n")
            elif user_manager._has("pw"):
                f.write("```bash\n")
                f.write(f"# BSD: Add user to {sudo_group} group\n")
                f.write(f"sudo pw groupmod {sudo_group} -m username\n\n")
                f.write("# Verify membership\n")
                f.write("id username\n")
                f.write("```\n\n")
            elif user_manager._has("dseditgroup"):
                f.write("```bash\n")
                f.write("# macOS: Add user to admin group\n")
                f.write("sudo dseditgroup -o edit -a username -t user admin\n")
                f.write("```\n\n")

            # Remove from sudoers
            f.write("#### Remove Sudo Access\n")
            if user_manager._has("gpasswd"):
                f.write("```bash\n")
                f.write(f"# Remove user from {sudo_group} group\n")
                f.write(f"sudo gpasswd -d username {sudo_group}\n\n")
                f.write("# Remove any custom sudoers entries\n")
                f.write("sudo rm -f /etc/sudoers.d/username\n")
                f.write("```\n\n")
            elif user_manager._has("deluser"):
                f.write("```bash\n")
                f.write(f"# Remove user from {sudo_group} group\n")
                f.write(f"sudo deluser username {sudo_group}\n\n")
                f.write("# Remove any custom sudoers entries\n")
                f.write("sudo rm -f /etc/sudoers.d/username\n")
                f.write("```\n\n")
            elif user_manager._has("pw"):
                f.write("```bash\n")
                f.write(f"# BSD: Remove user from {sudo_group} group\n")
                f.write(f"sudo pw groupmod {sudo_group} -d username\n")
                f.write("```\n\n")

            # Lock/disable account
            f.write("#### Lock/Disable User Account\n")
            if user_manager._has("usermod"):
                f.write("```bash\n")
                f.write("# Lock account (Linux)\n")
                f.write("sudo usermod -L username\n\n")
                f.write("# Unlock account\n")
                f.write("sudo usermod -U username\n")
                f.write("```\n\n")
            elif user_manager._has("passwd"):
                f.write("```bash\n")
                f.write("# Lock account\n")
                f.write("sudo passwd -l username\n\n")
                f.write("# Unlock account\n")
                f.write("sudo passwd -u username\n")
                f.write("```\n\n")
            elif user_manager._has("pw"):
                f.write("```bash\n")
                f.write("# BSD: Lock account\n")
                f.write("sudo pw lock username\n\n")
                f.write("# Unlock account\n")
                f.write("sudo pw unlock username\n")
                f.write("```\n\n")

        # Log analysis section
        f.write("### Log Analysis\n\n")

        # Determine which logging systems are in use
        has_systemd = self.server_info.init_system == "systemd"

        f.write("#### View Recent Authentication Logs\n")
        if has_systemd:
            f.write("```bash\n")
            f.write("# View SSH login attempts (last 100 lines)\n")
            f.write("sudo journalctl -u ssh -n 100\n\n")
            f.write("# View auth logs in real-time\n")
            f.write("sudo journalctl -u ssh -f\n\n")
            f.write("# View all authentication events\n")
            f.write("sudo journalctl -t sshd -t sudo --since '1 hour ago'\n")
            f.write("```\n\n")

        f.write("```bash\n")
        f.write("# Traditional auth log files\n")
        f.write("sudo tail -100 /var/log/auth.log     # Debian/Ubuntu\n")
        f.write("sudo tail -100 /var/log/secure       # RHEL/CentOS/Fedora\n\n")
        f.write("# Follow logs in real-time\n")
        f.write("sudo tail -f /var/log/auth.log\n\n")
        f.write("# Search for failed login attempts\n")
        f.write("sudo grep 'Failed password' /var/log/auth.log | tail -20\n\n")
        f.write("# Search for successful logins\n")
        f.write("sudo grep 'Accepted password' /var/log/auth.log | tail -20\n")
        f.write("```\n\n")

        f.write("### Active Session Monitoring\n\n")
        f.write("```bash\n")
        f.write("# Show currently logged in users\n")
        f.write("who\n")
        f.write("w\n\n")
        f.write("# Show recent login history\n")
        f.write("last -20\n\n")
        f.write("# Show failed login attempts\n")
        f.write("lastb -20  # (requires root)\n\n")
        f.write("# Kill a user's session\n")
        f.write("sudo pkill -u username\n\n")
        f.write("# Monitor active SSH connections\n")
        f.write("sudo netstat -tnpa | grep 'ESTABLISHED.*sshd'\n")
        f.write("# OR on systems with ss:\n")
        f.write("sudo ss -tnp | grep sshd\n")
        f.write("```\n\n")

        f.write("### Network Monitoring\n\n")
        f.write("```bash\n")
        f.write("# Show listening ports and services\n")
        f.write("sudo netstat -tulpn  # OR: sudo ss -tulpn\n\n")
        f.write("# Show active connections\n")
        f.write("sudo netstat -tunp   # OR: sudo ss -tunp\n\n")
        f.write("# Monitor incoming connections in real-time\n")
        f.write("watch -n 1 'sudo ss -tunp'\n")
        f.write("```\n\n")

        f.write("### Process Monitoring\n\n")
        f.write("```bash\n")
        f.write("# Show processes by user\n")
        f.write("ps aux | grep username\n\n")
        f.write("# Show process tree\n")
        f.write("pstree -p\n\n")
        f.write("# Monitor system resources\n")
        f.write("top\n")
        f.write("htop  # if installed\n\n")
        f.write("# Find suspicious processes\n")
        f.write("ps aux | grep -E '(nc|ncat|socat|python -m|perl|ruby)'\n")
        f.write("```\n\n")

        f.write("### Firewall Management\n\n")
        firewall_results = results.get("firewall_hardening", [])
        firewall_backend = None
        for r in firewall_results:
            if "firewalld" in r.command or "firewall-cmd" in r.command:
                firewall_backend = "firewalld"
                break
            elif "ufw" in r.command:
                firewall_backend = "ufw"
                break
            elif (
                "iptables" in r.command
                and "nft" not in r.command
                and "ufw" not in r.command
            ):
                firewall_backend = "iptables"
                break
            elif "nft" in r.command or "nftables" in r.command:
                firewall_backend = "nftables"
                break
            elif "pfctl" in r.command:
                firewall_backend = "pf"
                break
            elif "ipfw" in r.command:
                firewall_backend = "ipfw"
                break

        if firewall_backend == "firewalld":
            f.write("**Firewall Backend**: `firewalld`\n\n")

            # Check if using nftables or iptables backend
            uses_nftables = False
            for r in firewall_results:
                if "nft" in r.output.lower() or "nftables" in r.output.lower():
                    uses_nftables = True
                    break

            f.write("#### Status & Inspection\n")
            f.write("```bash\n")
            f.write("# Check firewall status\n")
            f.write("sudo firewall-cmd --state\n\n")
            f.write("# List current rules for all zones\n")
            f.write("sudo firewall-cmd --list-all\n\n")
            f.write("# List rules for specific zone\n")
            f.write("sudo firewall-cmd --zone=drop --list-all\n")
            f.write("sudo firewall-cmd --zone=trusted --list-all\n")
            f.write("```\n\n")

            f.write("#### Allow Ingress (Incoming) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow incoming TCP port (temporary - until reboot)\n")
            f.write("sudo firewall-cmd --add-port=8080/tcp\n\n")
            f.write("# Allow incoming TCP port (permanent)\n")
            f.write("sudo firewall-cmd --permanent --add-port=8080/tcp\n")
            f.write("sudo firewall-cmd --reload\n\n")
            f.write("# Allow incoming from specific IP\n")
            f.write(
                "sudo firewall-cmd --permanent --add-rich-rule='rule family=ipv4 source address=10.0.0.5 accept'\n"
            )
            f.write("sudo firewall-cmd --reload\n")
            f.write("```\n\n")

            f.write("#### Allow Egress (Outgoing) Traffic\n")
            f.write("```bash\n")
            f.write("# Egress rules require direct rules or rich rules\n")
            f.write("# Allow outbound to specific port (all users)\n")
            f.write(
                "sudo firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -p tcp --dport 3306 -j ACCEPT\n"
            )
            f.write("sudo firewall-cmd --reload\n")
            f.write("```\n\n")

            if uses_nftables:
                f.write("#### Advanced: User-Based Filtering (nftables backend)\n")
                f.write("```bash\n")
                f.write("# Allow port 80 outbound ONLY for nginx user (UID-based)\n")
                f.write("# First, get the UID of nginx user:\n")
                f.write("id -u nginx  # Example output: 33\n\n")
                f.write("# Create custom nftables table for user filtering\n")
                f.write("sudo nft add table inet user_filter\n")
                f.write(
                    "sudo nft add chain inet user_filter output '{ type filter hook output priority -10 ; }'\n\n"
                )
                f.write("# Allow nginx user (UID 33) to access port 80\n")
                f.write(
                    "sudo nft add rule inet user_filter output tcp dport 80 meta skuid 33 ct state new,established accept\n\n"
                )
                f.write("# Save configuration\n")
                f.write("sudo nft list ruleset > /etc/nftables/user_filter.nft\n")
                f.write("```\n\n")
            else:
                f.write("#### Advanced: User-Based Filtering (iptables backend)\n")
                f.write("```bash\n")
                f.write("# Allow port 80 outbound ONLY for nginx user (UID-based)\n")
                f.write("# First, get the UID of nginx user:\n")
                f.write("id -u nginx  # Example output: 33\n\n")
                f.write("# Allow nginx user (UID 33) to access port 80\n")
                f.write(
                    "sudo firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 1 \\\n"
                )
                f.write("  -p tcp --dport 80 -m owner --uid-owner 33 \\\n")
                f.write("  -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT\n\n")
                f.write("# Reload to apply\n")
                f.write("sudo firewall-cmd --reload\n")
                f.write("```\n\n")
        elif firewall_backend == "ufw":
            f.write("**Firewall Backend**: `ufw` (Uncomplicated Firewall)\n\n")

            f.write("#### Status & Inspection\n")
            f.write("```bash\n")
            f.write("# Check firewall status\n")
            f.write("sudo ufw status verbose\n\n")
            f.write("# List rules with numbers\n")
            f.write("sudo ufw status numbered\n\n")
            f.write("# Show listening ports\n")
            f.write("sudo ufw show listening\n")
            f.write("```\n\n")

            f.write("#### Allow Ingress (Incoming) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow incoming TCP port 8080\n")
            f.write("sudo ufw allow 8080/tcp\n\n")
            f.write("# Allow incoming UDP port 5353\n")
            f.write("sudo ufw allow 5353/udp\n\n")
            f.write("# Allow from specific IP (all traffic)\n")
            f.write("sudo ufw allow from 10.0.0.5\n\n")
            f.write("# Allow specific IP to specific port\n")
            f.write("sudo ufw allow from 10.0.0.5 to any port 22\n")
            f.write("```\n\n")

            f.write("#### Allow Egress (Outgoing) Traffic\n")
            f.write("```bash\n")
            f.write(
                "# UFW primarily manages incoming. For outbound, use iptables directly:\n"
            )
            f.write("# Allow outbound to TCP port 3306 (MySQL)\n")
            f.write(
                "sudo iptables -I ufw-before-output -p tcp --dport 3306 -j ACCEPT\n\n"
            )
            f.write("# Allow outbound to specific IP:port\n")
            f.write(
                "sudo iptables -I ufw-before-output -d 10.0.1.100 -p tcp --dport 5432 -j ACCEPT\n"
            )
            f.write("```\n\n")

            f.write("#### Advanced: User-Based Filtering\n")
            f.write("```bash\n")
            f.write(
                "# UFW doesn't support user matching natively, use iptables injection:\n"
            )
            f.write("# Allow port 80 outbound ONLY for nginx user\n")
            f.write("# First, get the UID of nginx user:\n")
            f.write("id -u nginx  # Example output: 33\n\n")
            f.write("# Allow nginx user (UID 33) to access port 80\n")
            f.write("sudo iptables -I ufw-before-output -p tcp --dport 80 \\\n")
            f.write("  -m owner --uid-owner 33 \\\n")
            f.write("  -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT\n\n")
            f.write("# Allow responses (inbound established)\n")
            f.write("sudo iptables -I ufw-before-input -p tcp --sport 80 \\\n")
            f.write("  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT\n")
            f.write("```\n\n")

            f.write("#### Useful Commands\n")
            f.write("```bash\n")
            f.write("# Enable UFW\n")
            f.write("sudo ufw enable\n\n")
            f.write("# Disable UFW (emergency)\n")
            f.write("sudo ufw disable\n\n")
            f.write("# Delete a rule by number\n")
            f.write("sudo ufw status numbered  # Find rule number\n")
            f.write("sudo ufw delete 5         # Delete rule #5\n\n")
            f.write("# Reset to defaults (CAREFUL!)\n")
            f.write("sudo ufw reset\n")
            f.write("```\n\n")
        elif firewall_backend == "iptables":
            f.write("**Firewall Backend**: `iptables`\n\n")

            f.write("#### Status & Inspection\n")
            f.write("```bash\n")
            f.write("# List all rules with line numbers\n")
            f.write("sudo iptables -L -v -n --line-numbers\n\n")
            f.write("# List specific chain (INPUT/OUTPUT/FORWARD)\n")
            f.write("sudo iptables -L INPUT -v -n\n")
            f.write("sudo iptables -L OUTPUT -v -n\n")
            f.write("```\n\n")

            f.write("#### Allow Ingress (Incoming) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow incoming TCP port 8080\n")
            f.write("sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT\n\n")
            f.write("# Allow incoming UDP port 5353 (mDNS example)\n")
            f.write("sudo iptables -A INPUT -p udp --dport 5353 -j ACCEPT\n\n")
            f.write("# Allow from specific IP (all traffic)\n")
            f.write("sudo iptables -A INPUT -s 10.0.0.5 -j ACCEPT\n")
            f.write("```\n\n")

            f.write("#### Allow Egress (Outgoing) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow outbound to TCP port 3306 (MySQL example)\n")
            f.write("sudo iptables -A OUTPUT -p tcp --dport 3306 -j ACCEPT\n\n")
            f.write("# Allow outbound to specific IP:port\n")
            f.write(
                "sudo iptables -A OUTPUT -d 10.0.1.100 -p tcp --dport 5432 -j ACCEPT\n"
            )
            f.write("```\n\n")

            f.write("#### Advanced: User-Based Filtering\n")
            f.write("```bash\n")
            f.write("# Allow port 80 outbound ONLY for nginx user\n")
            f.write("# First, get the UID of nginx user:\n")
            f.write("id -u nginx  # Example output: 33\n\n")
            f.write("# Allow nginx user (UID 33) to access port 80\n")
            f.write("sudo iptables -A OUTPUT -p tcp --dport 80 \\\n")
            f.write("  -m owner --uid-owner 33 \\\n")
            f.write("  -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT\n\n")
            f.write("# Allow port 443 for www-data user (UID 33 on Debian)\n")
            f.write("sudo iptables -A OUTPUT -p tcp --dport 443 \\\n")
            f.write("  -m owner --uid-owner 33 \\\n")
            f.write("  -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT\n\n")
            f.write("# Allow responses back (inbound established connections)\n")
            f.write("sudo iptables -A INPUT -p tcp --sport 80 \\\n")
            f.write("  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT\n")
            f.write("```\n\n")

            f.write("#### Save Rules\n")
            f.write("```bash\n")
            f.write("# Save rules (Debian/Ubuntu)\n")
            f.write("sudo iptables-save > /etc/iptables/rules.v4\n\n")
            f.write("# Save rules (RHEL/CentOS)\n")
            f.write("sudo service iptables save\n")
            f.write("```\n\n")
        elif firewall_backend == "nftables":
            f.write("**Firewall Backend**: `nftables`\n\n")

            f.write("#### Status & Inspection\n")
            f.write("```bash\n")
            f.write("# List all rules\n")
            f.write("sudo nft list ruleset\n\n")
            f.write("# List specific table\n")
            f.write("sudo nft list table inet filter\n\n")
            f.write("# List specific chain\n")
            f.write("sudo nft list chain inet filter input\n")
            f.write("sudo nft list chain inet filter output\n")
            f.write("```\n\n")

            f.write("#### Allow Ingress (Incoming) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow incoming TCP port 8080\n")
            f.write("sudo nft add rule inet filter input tcp dport 8080 accept\n\n")
            f.write("# Allow incoming UDP port 5353\n")
            f.write("sudo nft add rule inet filter input udp dport 5353 accept\n\n")
            f.write("# Allow from specific IP (all traffic)\n")
            f.write("sudo nft add rule inet filter input ip saddr 10.0.0.5 accept\n")
            f.write("```\n\n")

            f.write("#### Allow Egress (Outgoing) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow outbound to TCP port 3306 (MySQL)\n")
            f.write("sudo nft add rule inet filter output tcp dport 3306 accept\n\n")
            f.write("# Allow outbound to specific IP:port\n")
            f.write(
                "sudo nft add rule inet filter output ip daddr 10.0.1.100 tcp dport 5432 accept\n"
            )
            f.write("```\n\n")

            f.write("#### Advanced: User-Based Filtering\n")
            f.write("```bash\n")
            f.write("# Allow port 80 outbound ONLY for nginx user\n")
            f.write("# First, get the UID of nginx user:\n")
            f.write("id -u nginx  # Example output: 33\n\n")
            f.write("# Allow nginx user (UID 33) to access port 80\n")
            f.write("sudo nft add rule inet filter output tcp dport 80 \\\n")
            f.write("  meta skuid 33 ct state new,established accept\n\n")
            f.write("# Allow port 443 for www-data user\n")
            f.write("sudo nft add rule inet filter output tcp dport 443 \\\n")
            f.write("  meta skuid 33 ct state new,established accept\n\n")
            f.write("# Allow responses (inbound established connections)\n")
            f.write("sudo nft add rule inet filter input tcp sport 80 \\\n")
            f.write("  ct state established,related accept\n")
            f.write("```\n\n")

            f.write("#### Save Configuration\n")
            f.write("```bash\n")
            f.write("# Save to persistent config (Alpine)\n")
            f.write("sudo nft list ruleset > /etc/nftables.nft\n\n")
            f.write("# Save to persistent config (Debian/RHEL)\n")
            f.write("sudo nft list ruleset > /etc/nftables.conf\n")
            f.write("```\n\n")
        elif firewall_backend == "pf":
            f.write("**Firewall Backend**: `pf` (BSD)\n\n")

            f.write("#### Status & Inspection\n")
            f.write("```bash\n")
            f.write("# Show current rules\n")
            f.write("sudo pfctl -sr\n\n")
            f.write("# Show filter rules with statistics\n")
            f.write("sudo pfctl -vsr\n\n")
            f.write("# Show current state table (active connections)\n")
            f.write("sudo pfctl -ss\n")
            f.write("```\n\n")

            f.write("#### Allow Ingress (Incoming) Traffic\n")
            f.write(
                "PF rules are managed via `/etc/pf.conf`. Edit the config and reload.\n\n"
            )
            f.write("```bash\n")
            f.write("# Edit pf configuration\n")
            f.write("sudo vi /etc/pf.conf\n\n")
            f.write("# Add these lines for incoming port 8080:\n")
            f.write("# pass in proto tcp to any port 8080 keep state\n\n")
            f.write("# Reload rules after editing\n")
            f.write("sudo pfctl -f /etc/pf.conf\n")
            f.write("```\n\n")

            f.write("#### Allow Egress (Outgoing) Traffic\n")
            f.write("```bash\n")
            f.write("# Edit /etc/pf.conf and add:\n")
            f.write("# pass out proto tcp to any port 3306 keep state  # MySQL\n")
            f.write(
                "# pass out proto tcp to 10.0.1.100 port 5432 keep state  # Specific IP:port\n\n"
            )
            f.write("# Reload after editing\n")
            f.write("sudo pfctl -f /etc/pf.conf\n")
            f.write("```\n\n")

            f.write("#### User-Based Filtering\n")
            f.write(
                "**Note**: PF does not natively support user/UID-based filtering like Linux firewalls.\n"
            )
            f.write("For application-specific restrictions, consider using:\n")
            f.write("- Process jails or containers\n")
            f.write("- Application-level proxies (e.g., squid with ACLs)\n")
            f.write("- Network namespaces (if available on your BSD variant)\n\n")

            f.write("#### Useful Commands\n")
            f.write("```bash\n")
            f.write("# Enable PF\n")
            f.write("sudo pfctl -e\n\n")
            f.write("# Disable PF (emergency)\n")
            f.write("sudo pfctl -d\n\n")
            f.write("# Flush all states (kill existing connections)\n")
            f.write("sudo pfctl -F state\n")
            f.write("```\n\n")
        elif firewall_backend == "ipfw":
            f.write("**Firewall Backend**: `ipfw` (FreeBSD)\n\n")

            f.write("#### Status & Inspection\n")
            f.write("```bash\n")
            f.write("# List all rules\n")
            f.write("sudo ipfw list\n\n")
            f.write("# List rules with statistics\n")
            f.write("sudo ipfw show\n\n")
            f.write("# Show dynamic rules (active connections)\n")
            f.write("sudo ipfw -d list\n")
            f.write("```\n\n")

            f.write("#### Allow Ingress (Incoming) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow incoming TCP port 8080\n")
            f.write("# Rules use numbers - higher numbers = lower priority\n")
            f.write("sudo ipfw add 1000 allow tcp from any to me 8080 in\n\n")
            f.write("# Allow incoming UDP port 5353\n")
            f.write("sudo ipfw add 1010 allow udp from any to me 5353 in\n\n")
            f.write("# Allow from specific IP (all traffic)\n")
            f.write("sudo ipfw add 1020 allow ip from 10.0.0.5 to me in\n")
            f.write("```\n\n")

            f.write("#### Allow Egress (Outgoing) Traffic\n")
            f.write("```bash\n")
            f.write("# Allow outbound to TCP port 3306 (MySQL) with state tracking\n")
            f.write(
                "sudo ipfw add 2000 allow tcp from me to any 3306 out keep-state\n\n"
            )
            f.write("# Allow outbound to specific IP:port\n")
            f.write(
                "sudo ipfw add 2010 allow tcp from me to 10.0.1.100 5432 out keep-state\n"
            )
            f.write("```\n\n")

            f.write("#### Advanced: User-Based Filtering\n")
            f.write("```bash\n")
            f.write("# IPFW supports user/UID matching!\n")
            f.write("# Allow port 80 outbound ONLY for nginx user\n")
            f.write("# First, get the UID of nginx user:\n")
            f.write("id -u nginx  # Example output: 80\n\n")
            f.write("# Allow nginx user (UID 80) to access port 80\n")
            f.write(
                "sudo ipfw add 3000 allow tcp from me to any 80 out uid 80 keep-state\n\n"
            )
            f.write("# Allow port 443 for www user (UID 80)\n")
            f.write(
                "sudo ipfw add 3010 allow tcp from me to any 443 out uid 80 keep-state\n\n"
            )
            f.write("# Allow DNS for system users only (UID 0-999)\n")
            f.write(
                "sudo ipfw add 3020 allow udp from me to any 53 out uid 0-999 keep-state\n"
            )
            f.write("```\n\n")

            f.write("#### Useful Commands\n")
            f.write("```bash\n")
            f.write("# Flush all rules (CAREFUL - may lock you out!)\n")
            f.write("sudo ipfw -q flush\n\n")
            f.write("# Delete specific rule by number\n")
            f.write("sudo ipfw delete 1000\n\n")
            f.write("# Temporarily disable firewall (emergency)\n")
            f.write("sudo ipfw disable firewall\n\n")
            f.write("# Re-enable firewall\n")
            f.write("sudo ipfw enable firewall\n\n")
            f.write("# Add a catch-all deny rule (usually last rule)\n")
            f.write("sudo ipfw add 65000 deny ip from any to any\n")
            f.write("```\n\n")
        else:
            f.write(
                "**Firewall Backend**: Check `iptables`, `nftables`, `firewalld`, `ufw`, `pf`, or `ipfw` depending on your system.\n\n"
            )

        f.write("### Emergency Procedures\n\n")
        f.write("```bash\n")
        f.write("# Lock out a suspicious user immediately\n")
        f.write("sudo passwd -l username        # Lock password\n")
        f.write("sudo pkill -KILL -u username   # Kill all processes\n\n")
        f.write("# Block an IP address (iptables example)\n")
        f.write("sudo iptables -I INPUT -s SUSPICIOUS_IP -j DROP\n\n")
        f.write("# View currently blocked IPs (if using iptables)\n")
        f.write("sudo iptables -L INPUT -v -n | grep DROP\n\n")
        f.write("# Restart SSH service (if compromised config)\n")
        f.write("sudo systemctl restart sshd\n")
        f.write("# OR:\n")
        f.write("sudo service ssh restart\n")
        f.write("```\n\n")

        f.write("### Important File Locations\n\n")
        f.write("```\n")
        f.write("Configuration Files:\n")
        f.write("  /etc/ssh/sshd_config          SSH server configuration\n")
        f.write("  /etc/sudoers                  Sudo configuration\n")
        f.write("  /etc/passwd                   User accounts\n")
        f.write("  /etc/shadow                   Password hashes (requires root)\n")
        f.write("  /etc/group                    Group memberships\n\n")
        f.write("Log Files:\n")
        f.write("  /var/log/auth.log             Authentication logs (Debian/Ubuntu)\n")
        f.write("  /var/log/secure               Authentication logs (RHEL/CentOS)\n")
        f.write("  /var/log/sudo.log             Sudo command logs\n")
        f.write("  /var/log/ssh.log              SSH-specific logs (if configured)\n")
        f.write("  /var/log/audit/audit.log      Audit daemon logs\n")
        f.write("```\n\n")
