"""
SSH hardening module for CCDC framework
Enhanced with proper backup/rollback and connection testing
"""

import json
import logging
import os
from typing import List, Set
from fabric import Connection, Config
from .base import HardeningModule, HardeningCommand, PythonAction, HardeningResult
from ..discovery import OSFamily


logger = logging.getLogger(__name__)

# if the version is old add lines: 
# UsePrivilegeSeparation sandbox
# Protocol 2



class SSHHardeningModule(HardeningModule):
    """SSH hardening commands with backup, rollback, and connection testing"""
    
    def __init__(self, connection, server_info, os_family):
        super().__init__(connection, server_info, os_family)
        self.users_config = self._load_users_config()
        self.allowed_users = self._get_allowed_users()
        self.trapped_users = self._get_trapped_users()
        self.allowed_users = self.allowed_users | set(self.trapped_users)
    
    def get_name(self) -> str:
        return "ssh_hardening"
    
    def _load_users_config(self):
        """Load users configuration from users.json"""
        config_path = os.path.join(os.path.dirname(__file__), "../../users.json")
        try:
            with open(config_path, "r") as f:
                return json.load(f)
        except FileNotFoundError:
            logger.warning("users.json not found at %s", config_path)
            return {
                "regular_users": {},
                "super_users": {},
                "do_not_change_users": {"root": "system account"}
            }
        except json.JSONDecodeError as exc:
            logger.error("users.json is invalid: %s", exc)
            return {
                "regular_users": {},
                "super_users": {},
                "do_not_change_users": {"root": "system account"}
            }
    
    def _get_user_set(self, key: str) -> Set[str]:
        """Extract user set from config (handles dict or list)"""
        value = self.users_config.get(key, {})
        if isinstance(value, dict):
            return set(value.keys())
        elif isinstance(value, list):
            return set(value)
        return set()
    
    def _get_allowed_users(self) -> Set[str]:
        """Get all users that should be allowed to SSH (not trapped)"""
        regular = self._get_user_set("regular_users")
        super_users = self._get_user_set("super_users")
        do_not_change = self._get_user_set("do_not_change_users")
        return regular | super_users | do_not_change
    
    def _get_trapped_users(self) -> List[str]:
        """Get the 2 longest usernames from non-allowed users (likely not system accounts)"""
        current_valid_users = {
            user.username for user in self.server_info.users if user.valid_shell
        }
        non_allowed = current_valid_users - self.allowed_users
        # Sort by length (descending) then alphabetically, and take the top 2
        sorted_users = sorted(non_allowed, key=lambda u: (-len(u), u))
        trapped = sorted_users[:2]
        logger.info(f"Selected {len(trapped)} users for SSH honeypot trapping: {', '.join(trapped)}")
        return trapped
    
    def _generate_ssh_config(self) -> str:
        """Generate the complete SSH hardening configuration"""
        # Include both allowed users AND trapped users in AllowUsers directive
        all_allowed = sorted(self.allowed_users | set(self.trapped_users))
        allowed_users_str = " ".join(all_allowed)
        
        config = f"""# ===== BEGIN SSH HARDENING CONFIG =====
# Generated by MSU-BlueScripts SSH Hardening Module
# Do not manually edit this section

# Core Security Settings
Protocol 2
PermitRootLogin prohibit-password
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes

# Disable Legacy/Insecure Features
IgnoreRhosts yes
HostbasedAuthentication no
X11Forwarding no

# Authentication & Session Settings
MaxAuthTries 1
LoginGraceTime 60s
ClientAliveInterval 300
ClientAliveCountMax 2

# System Integration
UsePAM yes
SyslogFacility AUTH
AcceptEnv LANG LC_*

# User Access Control (includes trapped honeypot users)
AllowUsers {allowed_users_str}

# ===== END SSH HARDENING CONFIG =====

"""
        return config
    
    def _generate_trap_config(self) -> str:
        trapped_users_str = ' '.join(self.trapped_users)
        return f"""Match User {trapped_users_str}
    ForceCommand env -u $(env | cut -d= -f1) /bin/honeypot
    ChrootDirectory none
    AllowTcpForwarding no 
    X11Forwarding no 
    PermitTunnel no 
    GatewayPorts no 
    AllowAgentForwarding no 
    PermitOpen none
"""

    def get_commands(self) -> List[HardeningCommand]:
        commands = []
        
        # Create backup with timestamp and store backup path
        backup_timestamp = "$(date +%Y%m%d_%H%M%S)"
        
        # backup SSH config
        commands.append(HardeningCommand(
            command=f"cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.{backup_timestamp} && echo 'Backup created: /etc/ssh/sshd_config.backup.{backup_timestamp}'",
            description="Create timestamped SSH configuration backup",
            check_command="ls /etc/ssh/sshd_config.backup.* >/dev/null 2>&1 && echo backup_exists",
            requires_sudo=True
        ))
        
        # Store original config validation
        commands.append(HardeningCommand(
            command="sshd -t -f /etc/ssh/sshd_config && echo 'Original config valid'",
            description="Validate original SSH configuration",
            requires_sudo=True
        ))
        
        # Generate and prepend hardening config
        hardening_config = self._generate_ssh_config()
        commands.append(PythonAction(
            function=self._prepend_ssh_config,
            description="Prepend hardening configuration to sshd_config",
            args=(hardening_config,),
            requires_sudo=True
        ))
        
        # Append trapped users Match blocks to end of config (if any)
        trap_config = self._generate_trap_config()
        if self.trapped_users:
            commands.append(PythonAction(
                function=self._append_trapped_users,
                description=f"Append honeypot traps for users: {', '.join(self.trapped_users)}",
                args=(trap_config,),
                requires_sudo=True
            ))
        
        # Validate new configuration before applying
        commands.append(HardeningCommand(
            command="sshd -t -f /etc/ssh/sshd_config && echo 'New config valid'",
            description="Validate new SSH configuration",
            requires_sudo=True
        ))
        
        # Reload SSH service safely (reload instead of restart to avoid connection loss)
        reload_cmd = self._get_ssh_reload_command()
        commands.append(HardeningCommand(
            command=reload_cmd,
            description="Reload SSH service configuration",
            requires_sudo=True
        ))
        
        # Test SSH connectivity with Python function
        commands.append(PythonAction(
            function=self._test_ssh_connectivity,
            description="Test SSH connectivity after changes",
            requires_sudo=False
        ))
        
        return commands

    def _append_trapped_users(self, conn, server_info, trap_config ):
        """append hardening config to /etc/ssh/sshd_config"""
        try:
            # Read current config
            result = conn.sudo("cat /etc/ssh/sshd_config", hide=True, warn=True)
            if not result.ok:
                return HardeningResult(
                    success=False,
                    command="append_trap_sshd",
                    description="Read current sshd_config",
                    output="",
                    error=f"Failed to read sshd_config: {result.stderr}"
                )

            trap_config  = self._generate_trap_config()

            write_result = conn.sudo(
                f"printf '%s' '{trap_config}' >> /etc/ssh/sshd_config",
                hide=True,
                warn=True
            )
            
            if not write_result.ok:
                return HardeningResult(
                    success=False,
                    command="append_trap_sshd",
                    description="append config to file",
                    output="",
                    error=f"Failed to append trap config: {write_result.stderr}"
                )
                        
            trapped_count = len(self.trapped_users)
            
            return HardeningResult(
                success=True,
                command="append_trap_sshd",
                description="Prepend hardening configuration to sshd_config",
                output=f"Successfully appened SSH trapping config. Trapped users: {trapped_count}"
            )
            
        except Exception as e:
            logger.error(f"Error prepending SSH config: {e}")
            return HardeningResult(
                success=False,
                command="append_trap_sshd",
                description="Prepend hardening configuration to sshd_config",
                output="",
                error=str(e)
            )

    def _prepend_ssh_config(self, conn, server_info, hardening_config: str):
        """Prepend hardening config to /etc/ssh/sshd_config"""
        try:
            # Read current config
            result = conn.sudo("cat /etc/ssh/sshd_config", hide=True, warn=True)
            if not result.ok:
                return HardeningResult(
                    success=False,
                    command="prepend_ssh_config",
                    description="Read current sshd_config",
                    output="",
                    error=f"Failed to read sshd_config: {result.stderr}"
                )
            
            current_config = result.stdout
            
            # Combine: hardening config + original config
            new_config = hardening_config + current_config
            
            # Write to temporary file first
            temp_file = "/tmp/sshd_config.new"
            
            # Escape special characters for shell
            escaped_config = new_config.replace("'", "'\"'\"'")
            
            write_result = conn.sudo(
                f"printf '%s' '{escaped_config}' > {temp_file}",
                hide=True,
                warn=True
            )
            
            if not write_result.ok:
                return HardeningResult(
                    success=False,
                    command="prepend_ssh_config",
                    description="Write new config to temp file",
                    output="",
                    error=f"Failed to write temp config: {write_result.stderr}"
                )
            
            # Move temp file to actual location
            move_result = conn.sudo(
                f"mv {temp_file} /etc/ssh/sshd_config && chmod 644 /etc/ssh/sshd_config",
                hide=True,
                warn=True
            )
            
            if not move_result.ok:
                return HardeningResult(
                    success=False,
                    command="prepend_ssh_config",
                    description="Move new config to /etc/ssh/sshd_config",
                    output="",
                    error=f"Failed to move config: {move_result.stderr}"
                )
            
            allowed_count = len(self.allowed_users)
            
            return HardeningResult(
                success=True,
                command="prepend_ssh_config",
                description="Prepend hardening configuration to sshd_config",
                output=f"Successfully prepended SSH hardening config. Allowed users: {allowed_count}"
            )
            
        except Exception as e:
            logger.error(f"Error prepending SSH config: {e}")
            return HardeningResult(
                success=False,
                command="prepend_ssh_config",
                description="Prepend hardening configuration to sshd_config",
                output="",
                error=str(e)
            )
    
    def _test_ssh_connectivity(self, conn, server_info):
        """Test SSH connectivity after configuration changes with automatic rollback on failure"""
        import logging
        logger = logging.getLogger(__name__)
        
        try:
            # Get connection details from server_info
            host = server_info.credentials.host
            user = server_info.credentials.user
            port = getattr(server_info.credentials, 'port', 22)
            password = getattr(server_info.credentials, 'password', None)
            key_file = getattr(server_info.credentials, 'key_file', None)
            
            logger.info(f"Testing SSH connectivity to {host}:{port} as {user}")
            
            # Set up connection configuration
            connect_kwargs = {'allow_agent': False, 'look_for_keys': False}
            config_overrides = {
                'sudo': {'password': password},
                'load_ssh_configs': False
            }
            
            if key_file:
                connect_kwargs['key_filename'] = key_file
            elif password:
                connect_kwargs['password'] = password
                
            if port != 22:
                connect_kwargs['port'] = port
                
            config = Config(overrides=config_overrides)
            
            # Test new connection with a timeout
            test_success = False
            error_msg = None
            
            try:
                with Connection(host, user=user, config=config, connect_kwargs=connect_kwargs) as test_conn:
                    # Simple connectivity test
                    result = test_conn.run('echo "SSH test successful"', hide=True, warn=True, timeout=10)
                    test_success = result.ok
                    if not test_success:
                        error_msg = f"SSH test command failed: {result.stderr}"
                        
            except Exception as e:
                test_success = False
                error_msg = f"SSH connection failed: {str(e)}"
                
            if test_success:
                return HardeningResult(
                    success=True,
                    command="python_function:_test_ssh_connectivity",
                    description="Test SSH connectivity after changes",
                    output="SSH connectivity test successful - new configuration is working"
                )
            else:
                # Connection failed - attempt automatic rollback
                logger.warning(f"SSH connectivity test failed: {error_msg}")
                logger.info("Attempting automatic rollback of SSH configuration...")
                
                # Find the most recent backup
                backup_result = conn.run("ls -t /etc/ssh/sshd_config.backup.* 2>/dev/null | head -1", 
                                       hide=True, warn=True)
                
                if backup_result.ok and backup_result.stdout.strip():
                    backup_file = backup_result.stdout.strip()
                    logger.info(f"Found backup file: {backup_file}")
                    
                    # Restore the backup
                    restore_result = conn.sudo(f"cp {backup_file} /etc/ssh/sshd_config", 
                                             hide=True, warn=True)
                    
                    if restore_result.ok:
                        # Restart SSH service
                        reload_cmd = self._get_ssh_reload_command()
                        restart_result = conn.sudo(reload_cmd, hide=True, warn=True)
                        
                        if restart_result.ok:
                            logger.info("SSH configuration rolled back successfully")
                            return HardeningResult(
                                success=False,
                                command="python_function:_test_ssh_connectivity",
                                description="Test SSH connectivity after changes",
                                output="SSH test failed, configuration rolled back automatically",
                                error=f"Original error: {error_msg}. Rollback completed successfully."
                            )
                        else:
                            logger.error("Failed to restart SSH service after rollback")
                    else:
                        logger.error("Failed to restore SSH configuration backup")
                else:
                    logger.error("No SSH configuration backup found for rollback")
                
                return HardeningResult(
                    success=False,
                    command="python_function:_test_ssh_connectivity",
                    description="Test SSH connectivity after changes",
                    output="SSH connectivity test failed",
                    error=f"SSH test failed: {error_msg}. Manual intervention may be required."
                )
                
        except Exception as e:
            logger.error(f"SSH connectivity test encountered an error: {e}")
            return HardeningResult(
                success=False,
                command="python_function:_test_ssh_connectivity",
                description="Test SSH connectivity after changes",
                output="SSH connectivity test encountered an error",
                error=str(e)
            )
    
    def _get_ssh_reload_command(self) -> str:
        """Get the appropriate SSH reload command for the OS (safer than restart)"""
        try:
            os_family = OSFamily(self.os_family)
            
            # Detect init system from server info
            init_system = getattr(self.server_info, 'init_system', 'unknown')
            
            if init_system == "systemd":
                if os_family == OSFamily.DEBIAN:
                    # Use reload instead of restart to avoid connection loss
                    return "systemctl reload ssh || sudo systemctl restart ssh"
                else:
                    return "systemctl reload sshd || sudo systemctl restart sshd"
            elif init_system == "openrc":
                return "rc-service sshd reload || sudo rc-service sshd restart"
            else:
                # For SysV init systems
                return "service sshd reload || sudo service sshd restart"
        except ValueError:
            # Fallback for unknown OS family
            return "service sshd reload || sudo service sshd restart"
