all:
  children:
    linux:
      children:
        redhat:
          hosts:
            rocky:
              ansible_host: 10.0.0.5
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
            centos:
              ansible_host: 10.0.0.6
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
            fedora:
              ansible_host: 10.0.0.4
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
        debian:
          hosts:
            debian:
              ansible_host: 10.0.0.7
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
        alpine:
          hosts:
            alpine:
              ansible_host: 10.0.0.3
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
        arch:
          hosts:
            arch:
              ansible_host: 10.0.0.8
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
        suse:
          hosts:
            opensuse:
              ansible_host: 10.0.0.9
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
        slackware:
          hosts:
            slackware:
              ansible_host: 10.0.0.10
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
        gentoo:
          hosts:
            gentoo:
              ansible_host: 10.0.0.11
              ansible_user: root
              ansible_port: 22
              ansible_private_key_file: /root/Desktop/MSU-BlueScripts/Linux/fabric_deploy/keys/test-root-key.private
  vars:
    ansible_python_interpreter: /root/python/bin/python3.12
